'use client';
import Link from 'next/link'
import type { NextPage } from "next";
import Head from "next/head";

import {Heading} from "./components/Heading";

import Button from "./components/Button";



  


//import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Testing Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
  <Heading />
  <Button text="Click Me" onClick={() => alert("Clicked!")} />
  <Link href="/about">About</Link>
</main>

    </div>
  );
};

export default Home;
